/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f401xx_gpio_driver.h"

/* Busy-wait delay function (~1ms per iteration at 16MHz default HSI clock) */
void delay_ms(uint32_t ms) {
    for (uint32_t i = 0; i < (ms * 1600); i++) {
        __asm("NOP");
    }
}

int main(void) {
    /* -------------------------------------------------------------
     * Task 1 Configuration: Onboard LED (PA5) & Onboard Button (PC13)
     * ------------------------------------------------------------- */
    GPIO_Handle_t OnboardLed = {0};
    OnboardLed.pGPIOx = GPIOA;
    OnboardLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
    OnboardLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    OnboardLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
    OnboardLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    OnboardLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_Init(&OnboardLed);

    GPIO_Handle_t UserBtn = {0};
    UserBtn.pGPIOx = GPIOC;
    UserBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
    UserBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
    UserBtn.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
    UserBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD; // External pull-up present on Nucleo
    GPIO_Init(&UserBtn);

    /* -------------------------------------------------------------
     * Task 2 Configuration: External LEDs on PA6 and PA7
     * ------------------------------------------------------------- */
    GPIO_Handle_t ExtLed1 = {0};
    ExtLed1.pGPIOx = GPIOA;
    ExtLed1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_6;
    ExtLed1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    ExtLed1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
    ExtLed1.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    ExtLed1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_Init(&ExtLed1);

    GPIO_Handle_t ExtLed2 = {0};
    ExtLed2.pGPIOx = GPIOA;
    ExtLed2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_7;
    ExtLed2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    ExtLed2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
    ExtLed2.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    ExtLed2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    GPIO_Init(&ExtLed2);

    // Initial state for Task 2: ExtLED1 ON, ExtLED2 OFF
    GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_6, GPIO_PIN_SET);
    GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_7, GPIO_PIN_RESET);

    uint32_t blink_counter = 0;

    while (1) {
        /* Task 1: Check onboard button press (PC13 is Active Low) */
        if (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == 0) {
            delay_ms(50); // Software debounce delay
            if (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == 0) {
                // Toggling alternative using read/write
                uint8_t current_state = GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_5);
                GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, !current_state);

                // Wait for button release to avoid continuous toggling
                while (GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == 0);
                delay_ms(50); // Debounce release
            }
        }

        /* Task 2: Alternating External LED Blink every 250ms */
        delay_ms(10); // Polling step
        blink_counter += 10;

        if (blink_counter >= 250) {
            // Toggling alternative using read/write
            uint8_t state6 = GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_6);
            uint8_t state7 = GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_7);

            GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_6, !state6);
            GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_7, !state7);

            blink_counter = 0;
        }
    }
}
